DROP TABLE IF EXISTS "authors";
CREATE TABLE authors
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(512),
    age         INTEGER,
    description VARCHAR(512),
    image       VARCHAR(512),
    CONSTRAINT pk_authors PRIMARY KEY (id)
);

DROP TABLE IF EXISTS "authors";
CREATE TABLE books
(
    isbn        VARCHAR(19) NOT NULL,
    title       VARCHAR(512),
    description VARCHAR(2048),
    image       VARCHAR(512),
    author_id   BIGINT,
    CONSTRAINT pk_books PRIMARY KEY (isbn)
);

ALTER TABLE books
    ADD CONSTRAINT FK_BOOKS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES authors (id);